// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  フォルダから音楽ファイルをインポート（バッチ処理最適化版） */
	importFolder: (folderPath: string, duplicateAction: DuplicateAction) => __TAURI_INVOKE<ImportResult>("import_folder", { folderPath, duplicateAction }),
	/**  ライブラリフォルダの一覧を取得 */
	getLibraryFolders: () => __TAURI_INVOKE<LibraryFolderList>("get_library_folders"),
	/**
	 *  ライブラリフォルダの記録を削除する
	 * 
	 *  `remove_tracks`がtrueなら、フォルダ内のトラックもライブラリから外す（ファイルは消さない）。
	 *  外したトラック数を返す。
	 */
	removeLibraryFolder: (folderId: string, removeTracks: boolean) => __TAURI_INVOKE<number>("remove_library_folder", { folderId, removeTracks }),
	/**
	 *  ライブラリフォルダを再スキャンし、追加・削除・変更されたファイルをライブラリに反映する
	 * 
	 *  フォルダが見つからない場合はエラーにする（トラックは外さない）。
	 */
	rescanLibraryFolder: (folderId: string) => __TAURI_INVOKE<RescanResult>("rescan_library_folder", { folderId }),
	/**  現在の設定を取得 */
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**
	 *  設定を保存
	 * 
	 *  保存後に`SettingsChanged`イベントを送り、設定ウィンドウ以外（メインウィンドウ）にも反映させる。
	 */
	saveSettings: (settings: Settings) => __TAURI_INVOKE<null>("save_settings", { settings }),
	/**  すべてのトラックを取得 */
	getAllTracks: () => __TAURI_INVOKE<Track[]>("get_all_tracks"),
	/**  トラックを検索（FTS5 + LIKEフォールバック） */
	searchTracks: (query: string) => __TAURI_INVOKE<Track[]>("search_tracks", { query }),
	/**  トラックをフィルタリング */
	filterTracks: (filters: FilterOptions) => __TAURI_INVOKE<Track[]>("filter_tracks", { filters }),
	/**  ユニークなアーティスト一覧を取得 */
	getUniqueArtists: () => __TAURI_INVOKE<string[]>("get_unique_artists"),
	/**  ユニークなアルバム一覧を取得 */
	getUniqueAlbums: () => __TAURI_INVOKE<string[]>("get_unique_albums"),
	/**  ユニークなジャンル一覧を取得 */
	getUniqueGenres: () => __TAURI_INVOKE<string[]>("get_unique_genres"),
	/**  アルバム一覧（グループ化）を取得 */
	getAlbumsGrouped: () => __TAURI_INVOKE<AlbumGroup[]>("get_albums_grouped"),
	/**  アーティスト一覧（グループ化）を取得 */
	getArtistsGrouped: () => __TAURI_INVOKE<ArtistGroup[]>("get_artists_grouped"),
	/**  ジャンル一覧（グループ化）を取得 */
	getGenresGrouped: () => __TAURI_INVOKE<GenreGroup[]>("get_genres_grouped"),
	/**  トラックのメタデータを更新（データベースのみ） */
	updateTrackMetadata: (trackId: string, metadata: Metadata) => __TAURI_INVOKE<null>("update_track_metadata", { trackId, metadata }),
	/**  トラックのメタデータを更新（ファイルとデータベース両方） */
	updateTrackMetadataWithFile: (trackId: string, metadata: Metadata) => __TAURI_INVOKE<null>("update_track_metadata_with_file", { trackId, metadata }),
	/**  複数トラックのメタデータを一括更新（データベースのみ） */
	updateMultipleTracksMetadata: (trackIds: string[], metadata: Metadata) => __TAURI_INVOKE<null>("update_multiple_tracks_metadata", { trackIds, metadata }),
	/**  プレイリストを作成 */
	createPlaylist: (name: string) => __TAURI_INVOKE<Playlist>("create_playlist", { name }),
	/**  すべてのプレイリストを取得 */
	getPlaylists: () => __TAURI_INVOKE<Playlist[]>("get_playlists"),
	/**  プレイリストを削除 */
	deletePlaylist: (playlistId: string) => __TAURI_INVOKE<null>("delete_playlist", { playlistId }),
	/**  プレイリストの名前を変更 */
	renamePlaylist: (playlistId: string, name: string) => __TAURI_INVOKE<null>("rename_playlist", { playlistId, name }),
	/**  プレイリストにトラックを追加 */
	addTrackToPlaylist: (playlistId: string, trackId: string) => __TAURI_INVOKE<null>("add_track_to_playlist", { playlistId, trackId }),
	/**  プレイリストからトラックを削除 */
	removeTrackFromPlaylist: (playlistId: string, trackId: string) => __TAURI_INVOKE<null>("remove_track_from_playlist", { playlistId, trackId }),
	/**  プレイリスト内のトラックを並び替え */
	reorderPlaylistTracks: (playlistId: string, trackIds: string[]) => __TAURI_INVOKE<null>("reorder_playlist_tracks", { playlistId, trackIds }),
	/**
	 *  トラックのファイルパスを取得
	 * 
	 *  asset protocolの静的スコープは空にしてあるため、ここで返すファイルだけを
	 *  その都度スコープへ追加する。これによりWebViewから`convertFileSrc`で読めるのは
	 *  ライブラリに登録済みのトラックに限られる。
	 */
	getTrackFilePath: (trackId: string) => __TAURI_INVOKE<string>("get_track_file_path", { trackId }),
	/**  現在再生中のトラックIDを設定 */
	setCurrentTrack: (trackId: string | null) => __TAURI_INVOKE<null>("set_current_track", { trackId }),
	/**  現在再生中のトラック情報を取得 */
	getCurrentTrack: () => __TAURI_INVOKE<{
	id: string,
	filePath: string,
	fileName: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	genre: string | null,
	year: number | null,
	trackNumber: number | null,
	discNumber: number | null,
	duration: number | null,
	fileSize: number,
	format: string,
	bitrate: number | null,
	sampleRate: number | null,
	isFavorite: boolean,
	rating: number,
	playCount: number,
	lastPlayedAt: string | null,
	createdAt: string,
	updatedAt: string,
	/**  音量の正規化に使うゲイン（タグにない項目は値なし） */
	replayGain: ReplayGain,
} | null>("get_current_track"),
	/**
	 *  トラックのファイルをシステムのファイルマネージャーで表示
	 * 
	 *  WebViewから任意のパスを指定できないよう、トラックIDからDB上のパスを解決する。
	 */
	showInFolder: (trackId: string) => __TAURI_INVOKE<null>("show_in_folder", { trackId }),
	/**
	 *  プロジェクトのページを既定のブラウザで開く
	 * 
	 *  WebViewから任意のURLを開けないよう、開く先は固定のURLに限る。
	 */
	openProjectPage: () => __TAURI_INVOKE<null>("open_project_page"),
	/**  お気に入りを切り替え */
	toggleFavorite: (trackId: string) => __TAURI_INVOKE<boolean>("toggle_favorite", { trackId }),
	/**  レーティングを設定 */
	setRating: (trackId: string, rating: number) => __TAURI_INVOKE<null>("set_rating", { trackId, rating }),
	/**  再生回数をインクリメント */
	incrementPlayCount: (trackId: string) => __TAURI_INVOKE<number>("increment_play_count", { trackId }),
	/**  お気に入りトラック一覧を取得 */
	getFavoriteTracks: () => __TAURI_INVOKE<Track[]>("get_favorite_tracks"),
	/**  最も再生されたトラック一覧を取得 */
	getMostPlayedTracks: (limit: number | null) => __TAURI_INVOKE<Track[]>("get_most_played_tracks", { limit }),
	/**  最近再生されたトラック一覧を取得 */
	getRecentlyPlayedTracks: (limit: number | null) => __TAURI_INVOKE<Track[]>("get_recently_played_tracks", { limit }),
	/**
	 *  トラックをライブラリから削除（データベースのみ）
	 *  ファイルは削除せず、データベースからのみ削除
	 */
	deleteTracksCommand: (trackIds: string[]) => __TAURI_INVOKE<number>("delete_tracks_command", { trackIds }),
	/**
	 *  トラックをライブラリとファイルシステムから削除
	 *  データベースとファイル両方を削除
	 */
	deleteTracksWithFilesCommand: (trackIds: string[]) => __TAURI_INVOKE<DeleteResult>("delete_tracks_with_files_command", { trackIds }),
	/**
	 *  ライブラリ全体のメタデータを更新
	 *  ファイルからtrack_number・disc_number・ReplayGainを再読み込み
	 *  （タイトルなどはDBだけで編集できるため、ファイルの内容で上書きしない）
	 */
	refreshLibraryMetadata: () => __TAURI_INVOKE<RefreshMetadataResult>("refresh_library_metadata"),
};

/** Events */
export const events = {
	importProgress: makeEvent<ImportProgress>("import-progress"),
	libraryChanged: makeEvent<LibraryChanged>("library-changed"),
	libraryScanProgress: makeEvent<LibraryScanProgress>("library-scan-progress"),
	openImportDialog: makeEvent<OpenImportDialog>("open-import-dialog"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
	showAboutDialog: makeEvent<ShowAboutDialog>("show-about-dialog"),
	toggleSidebar: makeEvent<ToggleSidebar>("toggle-sidebar"),
};

/* Constants */
export const DEFAULT_ACCENT_COLOR = "#3b82f6" as const;

export const LIBRARY_SCAN_INTERVALS = [0,15,30,60,360] as const;

export const MAX_CROSSFADE_SECONDS = 12 as const;

/* Types */
/**  アルバムグループ（アルバム表示用） */
export type AlbumGroup = {
	name: string,
	artist: string | null,
	trackCount: number,
	totalDuration: number,
	representativeTrackId: string,
	tracks: Track[],
};

/**
 *  アプリケーション全体で使用するエラー型
 * 
 *  serdeのadjacently tagged表現により `{ "code": "LOCK", "message": "..." }`
 *  形式でシリアライズされる。specta::Typeによりコードのリテラル型union
 *  としてTypeScriptへエクスポートされる。
 */
export type AppError = 
/**  ロック取得の失敗（DBロック・ステートロック） */
{ code: "LOCK"; message: string } | 
/**  データベース操作の失敗 */
{ code: "DATABASE"; message: string } | 
/**  対象（トラック・プレイリスト・ファイル等）が見つからない */
{ code: "NOT_FOUND"; message: string } | 
/**  入力バリデーションエラー */
{ code: "VALIDATION"; message: string } | 
/**  ファイルI/Oエラー */
{ code: "IO"; message: string } | 
/**  メタデータの抽出・書き込みエラー */
{ code: "METADATA"; message: string };

/**  アーティストグループ（アーティスト表示用） */
export type ArtistGroup = {
	name: string,
	albumCount: number,
	trackCount: number,
	totalDuration: number,
	representativeTrackId: string,
	albums: AlbumGroup[],
};

/**  削除失敗の詳細 */
export type DeleteFailure = {
	/**  トラックID */
	trackId: string,
	/**  ファイルパス */
	filePath: string,
	/**  失敗の理由 */
	reason: string,
};

/**  トラック削除の結果 */
export type DeleteResult = {
	/**  削除に成功したトラック数 */
	successCount: number,
	/**  削除に失敗したトラック数 */
	failedCount: number,
	/**  削除に失敗したトラックの詳細 */
	failedTracks: DeleteFailure[],
};

/**  重複ファイルの処理方法 */
export type DuplicateAction = "Skip" | "Replace";

/**  フィルタオプション */
export type FilterOptions = {
	artist?: string | null,
	album?: string | null,
	genre?: string | null,
};

/**  ジャンルグループ（ジャンル表示用） */
export type GenreGroup = {
	name: string,
	trackCount: number,
	totalDuration: number,
	representativeTrackId: string,
	tracks: Track[],
};

/**  インポートの進捗 */
export type ImportProgress = {
	/**  処理済みファイル数 */
	current: number,
	/**  総ファイル数 */
	total: number,
	/**  現在処理中のファイル名 */
	currentFile: string,
};

/**  フォルダから音楽ファイルをインポートする結果 */
export type ImportResult = {
	importedCount: number,
	skippedCount: number,
	errorCount: number,
	errors: string[],
};

/**  表示の言語 */
export type Language = 
/**  日本語 */
"ja" | 
/**  英語 */
"en";

/**
 *  再スキャン・ライブラリフォルダの削除で、ライブラリのトラックが変わった
 * 
 *  設定ウィンドウでの操作を、メインウィンドウの一覧（Queryのキャッシュ）に反映する。
 */
export type LibraryChanged = null;

/**  ライブラリフォルダ（一覧表示用） */
export type LibraryFolder = {
	id: string,
	path: string,
	/**  フォルダ内のトラック数 */
	trackCount: number,
	/**  フォルダが今も存在するか（外付けドライブが外れている場合などはfalse） */
	exists: boolean,
	addedAt: string,
	lastScannedAt: string | null,
};

/**  ライブラリフォルダの一覧 */
export type LibraryFolderList = {
	folders: LibraryFolder[],
	/**
	 *  どのライブラリフォルダにも属さないトラック数（フォルダの記録を始める前に
	 *  インポートした曲など。同じフォルダをインポートし直すと登録される）
	 */
	unregisteredTrackCount: number,
};

/**  ライブラリフォルダの再スキャンの進捗 */
export type LibraryScanProgress = {
	/**  読み込み済みファイル数（追加・変更のあったファイルのみ数える） */
	current: number,
	/**  読み込むファイルの総数 */
	total: number,
	/**  現在処理中のファイル名 */
	currentFile: string,
};

/**  メタデータのデータモデル */
export type Metadata = {
	title?: string | null,
	artist?: string | null,
	album?: string | null,
	genre?: string | null,
	year?: number | null,
	trackNumber?: number | null,
	discNumber?: number | null,
	albumArtist?: string | null,
	composer?: string | null,
};

/**  メニュー「フォルダをインポート...」: インポートダイアログを開く */
export type OpenImportDialog = null;

/**  プレイリストのデータモデル */
export type Playlist = {
	id: string,
	name: string,
	description: string | null,
	tracks: PlaylistTrack[],
	createdAt: string,
	updatedAt: string,
};

/**  プレイリスト内のトラック情報 */
export type PlaylistTrack = {
	trackId: string,
	position: number,
	addedAt: string,
};

/**  メタデータ更新の結果 */
export type RefreshMetadataResult = {
	updatedCount: number,
	skippedCount: number,
	errorCount: number,
	errors: string[],
};

/**
 *  音量の正規化に使うゲインとピーク（ReplayGainのタグ、またはEBU R128のタグから読み取る）
 * 
 *  ゲインはReplayGainの基準（-18 LUFS）に合わせたdB。ピークは最大振幅（1.0がフルスケール）。
 */
export type ReplayGain = {
	trackGain: number | null,
	trackPeak: number | null,
	albumGain: number | null,
	albumPeak: number | null,
};

/**  再スキャンの結果 */
export type RescanResult = {
	/**  新しく追加したトラック数 */
	addedCount: number,
	/**  変更を読み直したトラック数 */
	updatedCount: number,
	/**  ファイルが見つからなくなり、ライブラリから外したトラック数 */
	removedCount: number,
	errorCount: number,
	errors: string[],
	/**  音楽ファイルが1件も見つからなかったため、ライブラリから外さなかった */
	removalSkipped: boolean,
};

/**  アプリケーション設定 */
export type Settings = {
	/**  表示の言語 */
	language: Language,
	/**  起動時に開く画面 */
	startupPage: StartupPage,
	/**  画面の配色 */
	theme: Theme,
	/**  アクセントカラー（`#rrggbb`） */
	accentColor: string,
	/**  音量の正規化 */
	volumeNormalization: VolumeNormalization,
	/**  ギャップレス再生（次の曲を先読みし、曲間に無音を入れずに続ける） */
	gaplessPlayback: boolean,
	/**  クロスフェードの秒数（0でクロスフェードしない） */
	crossfadeSeconds: number,
	/**  ライブラリフォルダを監視し、ファイルの変更を自動で反映する */
	watchLibraryFolders: boolean,
	/**  ライブラリフォルダを定期的に再スキャンする間隔（分。0で再スキャンしない） */
	libraryScanIntervalMinutes: number,
};

/**  設定が保存された（設定ウィンドウでの変更をメインウィンドウに反映する） */
export type SettingsChanged = Settings;

/**  メニュー「Muspice について」: Aboutダイアログを表示する */
export type ShowAboutDialog = null;

/**  起動時に開く画面 */
export type StartupPage = 
/**  前回開いていた画面 */
"lastOpened" | 
/**  曲一覧 */
"songs";

/**  画面の配色 */
export type Theme = 
/**  ダーク */
"dark" | 
/**  ライト */
"light" | 
/**  OSの設定に従う */
"system";

/**  メニュー「サイドバーを表示/隠す」: サイドバーの表示を切り替える */
export type ToggleSidebar = null;

/**  音楽トラックのデータモデル */
export type Track = {
	id: string,
	filePath: string,
	fileName: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	genre: string | null,
	year: number | null,
	trackNumber: number | null,
	discNumber: number | null,
	duration: number | null,
	fileSize: number,
	format: string,
	bitrate: number | null,
	sampleRate: number | null,
	isFavorite: boolean,
	rating: number,
	playCount: number,
	lastPlayedAt: string | null,
	createdAt: string,
	updatedAt: string,
	/**  音量の正規化に使うゲイン（タグにない項目は値なし） */
	replayGain: ReplayGain,
};

/**  音量の正規化（ReplayGain） */
export type VolumeNormalization = 
/**  補正しない */
"off" | 
/**  トラック単位のゲインで補正する（ない場合はアルバム単位） */
"track" | 
/**  アルバム単位のゲインで補正する（ない場合はトラック単位） */
"album";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

