// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  フォルダから音楽ファイルをインポート（バッチ処理最適化版） */
	importFolder: (folderPath: string, duplicateAction: DuplicateAction) => __TAURI_INVOKE<ImportResult>("import_folder", { folderPath, duplicateAction }),
	/**
	 *  ライブラリフォルダの一覧を取得
	 * 
	 *  フォルダの存在確認は、外れたネットワークドライブなどで時間がかかることがあるため、
	 *  ブロッキング処理用スレッドで行う。
	 */
	getLibraryFolders: () => __TAURI_INVOKE<LibraryFolderList>("get_library_folders"),
	/**
	 *  ライブラリフォルダの記録を削除する
	 * 
	 *  `remove_tracks`がtrueなら、フォルダ内のトラックもライブラリから外す（ファイルは消さない）。
	 *  外したトラック数を返す。
	 */
	removeLibraryFolder: (folderId: string, removeTracks: boolean) => __TAURI_INVOKE<number>("remove_library_folder", { folderId, removeTracks }),
	/**
	 *  ライブラリフォルダを再スキャンし、追加・移動・削除・変更されたファイルをライブラリに反映する
	 * 
	 *  フォルダが見つからない場合はエラーにする（トラックは見つからない曲にしない）。
	 */
	rescanLibraryFolder: (folderId: string) => __TAURI_INVOKE<RescanResult>("rescan_library_folder", { folderId }),
	/**
	 *  見つからない曲（ファイルが見つからなくなったトラック）を、すべてライブラリから外す
	 * 
	 *  外したトラック数を返す。ファイルには触れない。
	 */
	removeMissingTracks: () => __TAURI_INVOKE<number>("remove_missing_tracks"),
	/**
	 *  登録済みのデバイスの一覧を取得する
	 * 
	 *  接続の確認は、外れたネットワークドライブなどで時間がかかることがあるため、
	 *  ブロッキング処理用スレッドで行う。
	 */
	getSyncDevices: () => __TAURI_INVOKE<SyncDevice[]>("get_sync_devices"),
	/**
	 *  フォルダを転送先デバイスとして登録する
	 * 
	 *  フォルダに管理ファイルがある場合は、そのデバイスとして扱う（登録済みなら転送先を
	 *  更新し、未登録なら管理ファイルを引き継いで登録する）。なければ新しく作る。
	 */
	registerSyncDevice: (folderPath: string, name: string) => __TAURI_INVOKE<SyncDevice>("register_sync_device", { folderPath, name }),
	/**  デバイスの設定（名前と同期する対象）を更新する */
	updateSyncDevice: (deviceId: string, config: SyncDeviceConfig) => __TAURI_INVOKE<SyncDevice>("update_sync_device", { deviceId, config }),
	/**
	 *  デバイスの転送先のフォルダを変える（マウント先が変わった場合や、カードを初期化した場合）
	 * 
	 *  フォルダに別のデバイスの管理ファイルがある場合はエラーにする。管理ファイルがなければ、
	 *  このデバイスの管理ファイルを新しく作る。
	 */
	relinkSyncDevice: (deviceId: string, folderPath: string) => __TAURI_INVOKE<SyncDevice>("relink_sync_device", { deviceId, folderPath }),
	/**
	 *  デバイスの登録を解除する
	 * 
	 *  デバイス上の曲と管理ファイルは消さない（同じフォルダをもう一度登録すると、
	 *  コピー済みの曲を引き継ぐ）。
	 */
	removeSyncDevice: (deviceId: string) => __TAURI_INVOKE<null>("remove_sync_device", { deviceId }),
	/**
	 *  同期で行う処理の件数と必要な容量を調べる（デバイスには書き込まない）
	 * 
	 *  デバイスが接続されていない場合は`NOT_FOUND`。
	 */
	planDeviceSync: (deviceId: string) => __TAURI_INVOKE<DeviceSyncPlan>("plan_device_sync", { deviceId }),
	/**
	 *  デバイスへ同期する（削除 → リネーム → コピー → プレイリストの書き出し）
	 * 
	 *  `DeviceSyncProgress`を送る。同時に実行できる同期は1つで、実行中は`LOCK`。
	 *  同期する対象を選んでいない場合と、空き容量が足りない場合は`VALIDATION`。
	 *  ファイル単位の失敗は結果の`errors`に入れて続ける。
	 */
	runDeviceSync: (deviceId: string) => __TAURI_INVOKE<DeviceSyncResult>("run_device_sync", { deviceId }),
	/**  実行中の同期を中止する（コピー中のファイルの途中でも止める。実行中でなければ何もしない） */
	cancelDeviceSync: () => __TAURI_INVOKE<null>("cancel_device_sync"),
	/**  現在の設定を取得 */
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**
	 *  設定を保存
	 * 
	 *  保存後に`SettingsChanged`イベントを送り、設定ウィンドウ以外（メインウィンドウ）にも反映させる。
	 */
	saveSettings: (settings: Settings) => __TAURI_INVOKE<null>("save_settings", { settings }),
	/**  すべてのトラックを取得 */
	getAllTracks: () => __TAURI_INVOKE<Track[]>("get_all_tracks"),
	/**  トラックを検索（部分一致。大文字と小文字・全角と半角・ひらがなとカタカナを同じとみなす） */
	searchTracks: (query: string) => __TAURI_INVOKE<Track[]>("search_tracks", { query }),
	/**  トラックをフィルタリング */
	filterTracks: (filters: FilterOptions) => __TAURI_INVOKE<Track[]>("filter_tracks", { filters }),
	/**  ユニークなアーティスト一覧を取得 */
	getUniqueArtists: () => __TAURI_INVOKE<string[]>("get_unique_artists"),
	/**  ユニークなアルバム一覧を取得 */
	getUniqueAlbums: () => __TAURI_INVOKE<string[]>("get_unique_albums"),
	/**  ユニークなジャンル一覧を取得 */
	getUniqueGenres: () => __TAURI_INVOKE<string[]>("get_unique_genres"),
	/**  アルバムの一覧を取得（曲は含めない） */
	getAlbums: () => __TAURI_INVOKE<AlbumSummary[]>("get_albums"),
	/**
	 *  アルバムの曲を取得
	 * 
	 *  `artist`は、アルバムをまとめたアーティスト（`AlbumSummary`の`artist`）。
	 */
	getAlbumTracks: (album: string, artist: string | null) => __TAURI_INVOKE<Track[]>("get_album_tracks", { album, artist }),
	/**  アーティストの一覧を取得（アルバムと曲は含めない） */
	getArtists: () => __TAURI_INVOKE<ArtistSummary[]>("get_artists"),
	/**  アーティストのアルバムと曲を取得 */
	getArtistAlbums: (artist: string) => __TAURI_INVOKE<AlbumGroup[]>("get_artist_albums", { artist }),
	/**  ジャンルの一覧を取得（曲は含めない） */
	getGenres: () => __TAURI_INVOKE<GenreSummary[]>("get_genres"),
	/**  ジャンルの曲を取得 */
	getGenreTracks: (genre: string) => __TAURI_INVOKE<Track[]>("get_genre_tracks", { genre }),
	/**
	 *  トラックのメタデータを更新（ファイルのタグとデータベース）
	 * 
	 *  タイトル・アーティスト・アルバム・ジャンル・年は、値がなければタグからも取り除く。
	 */
	updateTrackMetadata: (trackId: string, metadata: Metadata) => __TAURI_INVOKE<null>("update_track_metadata", { trackId, metadata }),
	/**
	 *  複数トラックのメタデータを一括更新（ファイルのタグとデータベース）
	 * 
	 *  値がある項目だけを変える。ファイルへ書き込めなかったトラックは、データベースも変えずに
	 *  結果の`errors`へ理由を入れ、残りのトラックの更新を続ける。
	 */
	updateMultipleTracksMetadata: (trackIds: string[], metadata: Metadata) => __TAURI_INVOKE<BulkUpdateResult>("update_multiple_tracks_metadata", { trackIds, metadata }),
	/**
	 *  アプリ内（データベース）だけにある編集内容・評価を、ファイルのタグへ書き出す
	 * 
	 *  ファイルと違う値だけを書き込み、その後ファイルを読み直してデータベースに反映する
	 *  （終わると、データベースはファイルの内容と一致する）。メタデータの編集がファイルへ
	 *  書き込まれなかった頃の内容を、ファイルへ移すために使う。
	 */
	writeLibraryMetadataToFiles: () => __TAURI_INVOKE<WriteMetadataResult>("write_library_metadata_to_files"),
	/**  プレイリストを作成 */
	createPlaylist: (name: string) => __TAURI_INVOKE<Playlist>("create_playlist", { name }),
	/**  すべてのプレイリストを取得 */
	getPlaylists: () => __TAURI_INVOKE<Playlist[]>("get_playlists"),
	/**  プレイリストの曲を取得（プレイリストの中の並び順） */
	getPlaylistTracks: (playlistId: string) => __TAURI_INVOKE<Track[]>("get_playlist_tracks", { playlistId }),
	/**  プレイリストを削除 */
	deletePlaylist: (playlistId: string) => __TAURI_INVOKE<null>("delete_playlist", { playlistId }),
	/**  プレイリストの名前を変更 */
	renamePlaylist: (playlistId: string, name: string) => __TAURI_INVOKE<null>("rename_playlist", { playlistId, name }),
	/**
	 *  プレイリストにトラックを追加（複数のトラックを、渡した順に追加する）
	 * 
	 *  すでに入っているトラックは飛ばし、追加したトラック数を返す。
	 *  見つからないトラックがある場合は、1曲も追加しない。
	 */
	addTracksToPlaylist: (playlistId: string, trackIds: string[]) => __TAURI_INVOKE<number>("add_tracks_to_playlist", { playlistId, trackIds }),
	/**  プレイリストからトラックを削除 */
	removeTrackFromPlaylist: (playlistId: string, trackId: string) => __TAURI_INVOKE<null>("remove_track_from_playlist", { playlistId, trackId }),
	/**  プレイリスト内のトラックを並び替え */
	reorderPlaylistTracks: (playlistId: string, trackIds: string[]) => __TAURI_INVOKE<null>("reorder_playlist_tracks", { playlistId, trackIds }),
	/**  現在再生中のトラックIDを設定 */
	setCurrentTrack: (trackId: string | null) => __TAURI_INVOKE<null>("set_current_track", { trackId }),
	/**  現在再生中のトラック情報を取得 */
	getCurrentTrack: () => __TAURI_INVOKE<{
	id: string,
	filePath: string,
	fileName: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	/**  アルバムアーティスト（タグにない曲は値なし。一覧では、ない場合に`artist`でまとめる） */
	albumArtist: string | null,
	genre: string | null,
	year: number | null,
	trackNumber: number | null,
	discNumber: number | null,
	duration: number | null,
	fileSize: number,
	format: string,
	bitrate: number | null,
	sampleRate: number | null,
	isFavorite: boolean,
	rating: number,
	/**  再生回数（曲の半分か4分を聴いた回数） */
	playCount: number,
	/**  スキップ回数（再生回数に数える前に、別の曲へ移った回数） */
	skipCount: number,
	/**  最後に再生回数に数えた日時 */
	lastPlayedAt: string | null,
	createdAt: string,
	updatedAt: string,
	/**  音量の正規化に使うゲイン（タグにない項目は値なし） */
	replayGain: ReplayGain,
	/**  ファイルが見つからない（再スキャンで見つからなくなった曲。利用者が外すまで残す） */
	isMissing: boolean,
} | null>("get_current_track"),
	/**
	 *  再生状態（音量・シャッフル・リピート・再生キュー・再生していた曲）を保存する
	 * 
	 *  `queue`は、キューが変わった時だけ渡す（nullなら、保存してあるキューから変えない）。
	 *  再生位置は保存しない。
	 */
	savePlaybackState: (cursor: PlaybackCursor, queue: {
	/**  再生する順のトラックID */
	trackIds: string[],
	/**  シャッフルする前の順のトラックID（シャッフルが有効な時だけ。解除した時に、この順へ戻す） */
	originalTrackIds: string[] | null,
} | null) => __TAURI_INVOKE<null>("save_playback_state", { cursor, queue }),
	/**
	 *  保存してある再生状態を取得する（起動時の復元用）
	 * 
	 *  ライブラリからなくなった曲・ファイルが見つからない曲は、キューから除いて返す。
	 */
	getPlaybackState: () => __TAURI_INVOKE<RestoredPlaybackState>("get_playback_state"),
	/**
	 *  トラックを頭から再生する（再生中の曲は止める）
	 * 
	 *  `token`は、フロントエンドが再生ごとに振る番号。この曲についての`PlaybackEvent`に付いて返る。
	 */
	playbackPlay: (trackId: string, token: number) => __TAURI_INVOKE<PlaybackTrackInfo>("playback_play", { trackId, token }),
	/**
	 *  再生中の曲に続けて再生するトラックを用意する（nullで取り消す）
	 * 
	 *  用意しておくと、再生中の曲の終わりから切れ目なく続けて再生し（ギャップレス再生）、
	 *  切り替わった時点で`PlaybackEvent`の`advanced`が届く。
	 */
	playbackSetNext: (trackId: string | null, token: number) => __TAURI_INVOKE<null>("playback_set_next", { trackId, token }),
	/**  再生を一時停止する */
	playbackPause: () => __TAURI_INVOKE<null>("playback_pause"),
	/**  一時停止した再生を再開する */
	playbackResume: () => __TAURI_INVOKE<null>("playback_resume"),
	/**  再生中の曲の、指定した位置（秒）へ移動する */
	playbackSeek: (position: number | null) => __TAURI_INVOKE<null>("playback_seek", { position }),
	/**  音量（0.0〜1.0）を設定する */
	playbackSetVolume: (volume: number | null) => __TAURI_INVOKE<null>("playback_set_volume", { volume }),
	/**
	 *  イコライザの設定を変える（再生中の音にすぐに効く）
	 * 
	 *  `gains`は、バンドごとのゲイン（dB。31Hz〜16kHzの10個。範囲外の値は-12〜12に収める）。
	 *  設定はフロントエンドが保存しており（`equalizer.svelte.ts`）、起動時と変更のたびに送る。
	 */
	playbackSetEqualizer: (enabled: boolean, gains: (number | null)[]) => __TAURI_INVOKE<null>("playback_set_equalizer", { enabled, gains }),
	/**  再生を止める（再生中の曲・続けて再生する曲を手放す） */
	playbackStop: () => __TAURI_INVOKE<null>("playback_stop"),
	/**  出力デバイスの一覧を取得する */
	getOutputDevices: () => __TAURI_INVOKE<OutputDevice[]>("get_output_devices"),
	/**
	 *  プレーヤーバーの状態（曲・再生中かどうか・再生位置）を、OSへ伝える（nullは、再生している曲がない）
	 * 
	 *  OSのNow Playing（macOSのコントロールセンターなど）に表示され、メディアキーの操作が
	 *  このアプリへ届くようになる。対応していないOSでは何もしない。
	 *  フロントエンドは、前の呼び出しの結果を待ってから次を呼ぶ（順番が入れ替わらないようにする）。
	 */
	setNowPlaying: (update: {
	/**  再生中（一時停止中）の曲 */
	trackId: string,
	/**  再生中か（falseは一時停止中） */
	playing: boolean,
	/**  再生位置（曲の頭からの秒数） */
	position: number | null,
	/**  曲の長さ（秒。再生エンジンがファイルから読んだ値。分からなければnullで、ライブラリの値を使う） */
	duration: number | null,
} | null) => __TAURI_INVOKE<null>("set_now_playing", { update }),
	/**
	 *  トラックのファイルをシステムのファイルマネージャーで表示
	 * 
	 *  WebViewから任意のパスを指定できないよう、トラックIDからDB上のパスを解決する。
	 */
	showInFolder: (trackId: string) => __TAURI_INVOKE<null>("show_in_folder", { trackId }),
	/**
	 *  プロジェクトのページを既定のブラウザで開く
	 * 
	 *  WebViewから任意のURLを開けないよう、開く先は固定のURLに限る。
	 */
	openProjectPage: () => __TAURI_INVOKE<null>("open_project_page"),
	/**  お気に入りを切り替え */
	toggleFavorite: (trackId: string) => __TAURI_INVOKE<boolean>("toggle_favorite", { trackId }),
	/**
	 *  レーティングを設定（ファイルのタグへ書き込み、同じ値をデータベースに記録する）
	 * 
	 *  ファイルへ書き込めない場合はエラーにし、データベースも変えない。
	 */
	setRating: (trackId: string, rating: number) => __TAURI_INVOKE<null>("set_rating", { trackId, rating }),
	/**
	 *  再生回数をインクリメントし、再生履歴に追加する（新しい再生回数を返す）
	 * 
	 *  いつ数えるか（曲の半分か4分を聴いた時）は、フロントエンドの再生コントローラーが決める。
	 */
	incrementPlayCount: (trackId: string) => __TAURI_INVOKE<number>("increment_play_count", { trackId }),
	/**
	 *  スキップ回数をインクリメントする（新しいスキップ回数を返す）
	 * 
	 *  いつ数えるか（再生回数に数える前に、別の曲へ移った時）は、フロントエンドの再生コントローラーが決める。
	 */
	incrementSkipCount: (trackId: string) => __TAURI_INVOKE<number>("increment_skip_count", { trackId }),
	/**  お気に入りトラック一覧を取得 */
	getFavoriteTracks: () => __TAURI_INVOKE<Track[]>("get_favorite_tracks"),
	/**  最も再生されたトラック一覧を取得 */
	getMostPlayedTracks: (limit: number | null) => __TAURI_INVOKE<Track[]>("get_most_played_tracks", { limit }),
	/**
	 *  再生履歴を取得（新しい順。同じ曲が何度も出る。件数の上限はない）
	 * 
	 *  曲の情報は含めない（フロントエンドが、全曲の一覧からトラックIDで引く）。
	 */
	getPlayHistory: () => __TAURI_INVOKE<PlayHistoryEntry[]>("get_play_history"),
	/**
	 *  トラックをライブラリから削除（データベースのみ）
	 *  ファイルは削除せず、データベースからのみ削除
	 */
	deleteTracksCommand: (trackIds: string[]) => __TAURI_INVOKE<number>("delete_tracks_command", { trackIds }),
	/**
	 *  トラックをライブラリとファイルシステムから削除
	 *  データベースとファイル両方を削除
	 */
	deleteTracksWithFilesCommand: (trackIds: string[]) => __TAURI_INVOKE<DeleteResult>("delete_tracks_with_files_command", { trackIds }),
	/**
	 *  ライブラリ全体のメタデータを更新
	 * 
	 *  全トラックのファイルを読み直し、タグの内容（タイトルなど・評価・トラック番号・
	 *  ReplayGain）と長さなどをデータベースに反映する。お気に入り・再生回数は変えない。
	 */
	refreshLibraryMetadata: () => __TAURI_INVOKE<RefreshMetadataResult>("refresh_library_metadata"),
};

/** Events */
export const events = {
	deviceSyncProgress: makeEvent<DeviceSyncProgress>("device-sync-progress"),
	importProgress: makeEvent<ImportProgress>("import-progress"),
	libraryChanged: makeEvent<LibraryChanged>("library-changed"),
	libraryScanProgress: makeEvent<LibraryScanProgress>("library-scan-progress"),
	openImportDialog: makeEvent<OpenImportDialog>("open-import-dialog"),
	playbackControl: makeEvent<PlaybackControl>("playback-control"),
	playbackEvent: makeEvent<PlaybackEvent>("playback-event"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
	showAboutDialog: makeEvent<ShowAboutDialog>("show-about-dialog"),
	toggleSidebar: makeEvent<ToggleSidebar>("toggle-sidebar"),
};

/* Constants */
export const DEFAULT_ACCENT_COLOR = "#3b82f6" as const;

export const LIBRARY_SCAN_INTERVALS = [0,15,30,60,360] as const;

export const MAX_CROSSFADE_SECONDS = 12 as const;

/* Types */
/**  アルバムとその曲（アーティストの詳細で、アルバムごとに曲を表示するために使う） */
export type AlbumGroup = {
	name: string,
	artist: string | null,
	trackCount: number,
	totalDuration: number,
	representativeTrackId: string,
	tracks: Track[],
};

/**
 *  アルバムの一覧の1件（曲は含めない。曲は`get_album_tracks`で取得する）
 * 
 *  アルバムは「アルバムアーティスト（なければ曲のアーティスト）＋アルバム名」でまとめる。
 */
export type AlbumSummary = {
	name: string,
	/**  アルバムをまとめたアーティスト（アルバムアーティスト。なければ曲のアーティスト） */
	artist: string | null,
	trackCount: number,
	totalDuration: number,
	representativeTrackId: string,
};

/**
 *  アプリケーション全体で使用するエラー型
 * 
 *  serdeのadjacently tagged表現により `{ "code": "LOCK", "message": "..." }`
 *  形式でシリアライズされる。specta::Typeによりコードのリテラル型union
 *  としてTypeScriptへエクスポートされる。
 */
export type AppError = 
/**  ロック取得の失敗（DBロック・ステートロック） */
{ code: "LOCK"; message: string } | 
/**  データベース操作の失敗 */
{ code: "DATABASE"; message: string } | 
/**  対象（トラック・プレイリスト・ファイル等）が見つからない */
{ code: "NOT_FOUND"; message: string } | 
/**  入力バリデーションエラー */
{ code: "VALIDATION"; message: string } | 
/**  ファイルI/Oエラー */
{ code: "IO"; message: string } | 
/**  メタデータの抽出・書き込みエラー */
{ code: "METADATA"; message: string } | 
/**  再生エンジンのエラー（デコードできない・出力デバイスを使えない） */
{ code: "PLAYBACK"; message: string };

/**
 *  アーティストの一覧の1件（アルバムと曲は含めない。`get_artist_albums`で取得する）
 * 
 *  アーティストは、アルバムアーティスト（なければ曲のアーティスト）でまとめる。
 */
export type ArtistSummary = {
	name: string,
	albumCount: number,
	trackCount: number,
	totalDuration: number,
	representativeTrackId: string,
};

/**  一括編集の結果 */
export type BulkUpdateResult = {
	/**  ファイルとデータベースを更新できたトラック数 */
	updatedCount: number,
	/**  更新できなかったトラック数（ファイルが見つからない・書き込めないなど） */
	failedCount: number,
	/**  更新できなかったトラックの理由（ファイルごと） */
	errors: string[],
};

/**  削除失敗の詳細 */
export type DeleteFailure = {
	/**  トラックID */
	trackId: string,
	/**  ファイルパス */
	filePath: string,
	/**  失敗の理由 */
	reason: string,
};

/**  トラック削除の結果 */
export type DeleteResult = {
	/**  削除に成功したトラック数 */
	successCount: number,
	/**  削除に失敗したトラック数 */
	failedCount: number,
	/**  削除に失敗したトラックの詳細 */
	failedTracks: DeleteFailure[],
};

/**  同期で行う処理の件数と、必要な容量（同期の前の確認用） */
export type DeviceSyncPlan = {
	/**  コピーする曲数とサイズの合計（バイト） */
	copyCount: number,
	copyBytes: number,
	/**  デバイスから削除する曲数とサイズの合計（バイト） */
	deleteCount: number,
	deleteBytes: number,
	/**  デバイス上で名前を変える曲数（タグが変わって配置が変わった曲） */
	renameCount: number,
	/**  そのまま残す曲数 */
	unchangedCount: number,
	/**  書き出すプレイリスト数 */
	playlistCount: number,
	/**  元のファイルが見つからない曲数（コピーできない。コピー済みならデバイスに残す） */
	missingSourceCount: number,
	/**  デバイスの空き容量と、同期で増える容量（バイト） */
	freeBytes: number,
	requiredBytes: number,
	/**  空き容量が足りるか */
	hasEnoughSpace: boolean,
};

/**  デバイスへの同期の進捗（コピー中のファイル） */
export type DeviceSyncProgress = {
	/**  同期しているデバイス */
	deviceId: string,
	/**  コピーが済んだファイル数 */
	current: number,
	/**  コピーするファイルの総数 */
	total: number,
	/**  コピーが済んだバイト数と、コピーするバイト数の合計 */
	bytesDone: number,
	bytesTotal: number,
	/**  コピー中のファイル名 */
	currentFile: string,
};

/**  同期の結果 */
export type DeviceSyncResult = {
	copiedCount: number,
	deletedCount: number,
	renamedCount: number,
	/**  書き出したプレイリスト数 */
	playlistCount: number,
	errorCount: number,
	errors: string[],
	/**  途中で中止された */
	cancelled: boolean,
};

/**  重複ファイルの処理方法 */
export type DuplicateAction = "Skip" | "Replace";

/**  フィルタオプション */
export type FilterOptions = {
	artist?: string | null,
	album?: string | null,
	genre?: string | null,
};

/**  ジャンルの一覧の1件（曲は含めない。曲は`get_genre_tracks`で取得する） */
export type GenreSummary = {
	name: string,
	trackCount: number,
	totalDuration: number,
	representativeTrackId: string,
};

/**  インポートの進捗 */
export type ImportProgress = {
	/**  処理済みファイル数 */
	current: number,
	/**  総ファイル数 */
	total: number,
	/**  現在処理中のファイル名 */
	currentFile: string,
};

/**  フォルダから音楽ファイルをインポートする結果 */
export type ImportResult = {
	importedCount: number,
	skippedCount: number,
	/**  見つからない曲を、移動・改名された先のファイルに結び付けた数（新しい曲としては登録しない） */
	relinkedCount: number,
	errorCount: number,
	errors: string[],
};

/**  表示の言語 */
export type Language = 
/**  日本語 */
"ja" | 
/**  英語 */
"en";

/**
 *  再スキャン・ライブラリフォルダの削除で、ライブラリのトラックが変わった
 * 
 *  設定ウィンドウでの操作を、メインウィンドウの一覧（Queryのキャッシュ）に反映する。
 */
export type LibraryChanged = null;

/**  ライブラリフォルダ（一覧表示用） */
export type LibraryFolder = {
	id: string,
	path: string,
	/**  フォルダ内のトラック数 */
	trackCount: number,
	/**  フォルダが今も存在するか（外付けドライブが外れている場合などはfalse） */
	exists: boolean,
	addedAt: string,
	lastScannedAt: string | null,
};

/**  ライブラリフォルダの一覧 */
export type LibraryFolderList = {
	folders: LibraryFolder[],
	/**
	 *  どのライブラリフォルダにも属さないトラック数（フォルダの記録を始める前に
	 *  インポートした曲など。同じフォルダをインポートし直すと登録される）
	 */
	unregisteredTrackCount: number,
	/**  見つからない曲の数（ファイルが見つからなくなり、利用者が外すまで残しているトラック） */
	missingTrackCount: number,
};

/**  ライブラリフォルダの再スキャンの進捗 */
export type LibraryScanProgress = {
	/**  読み込み済みファイル数（追加・変更のあったファイルのみ数える） */
	current: number,
	/**  読み込むファイルの総数 */
	total: number,
	/**  現在処理中のファイル名 */
	currentFile: string,
};

/**  メタデータのデータモデル */
export type Metadata = {
	title?: string | null,
	artist?: string | null,
	album?: string | null,
	genre?: string | null,
	year?: number | null,
	trackNumber?: number | null,
	discNumber?: number | null,
	albumArtist?: string | null,
	composer?: string | null,
};

/**  フロントエンドから届く、プレーヤーバーの状態 */
export type NowPlayingUpdate = {
	/**  再生中（一時停止中）の曲 */
	trackId: string,
	/**  再生中か（falseは一時停止中） */
	playing: boolean,
	/**  再生位置（曲の頭からの秒数） */
	position: number | null,
	/**  曲の長さ（秒。再生エンジンがファイルから読んだ値。分からなければnullで、ライブラリの値を使う） */
	duration: number | null,
};

/**  メニュー「フォルダをインポート...」: インポートダイアログを開く */
export type OpenImportDialog = null;

/**  出力デバイス */
export type OutputDevice = {
	/**  デバイスを選ぶためのID（設定に保存する。接続し直しても変わらない） */
	id: string,
	/**  表示名 */
	name: string,
	/**  OSの既定の出力デバイスか */
	isDefault: boolean,
};

/**
 *  再生履歴の1件（再生回数に数えた再生）
 * 
 *  曲の情報は持たない（フロントエンドが、全曲の一覧のキャッシュからトラックIDで引く）。
 */
export type PlayHistoryEntry = {
	/**  履歴のID（同じ曲が何度も出るため、行の識別に使う） */
	id: number,
	trackId: string,
	/**  再生回数に数えた日時（RFC 3339。UTC） */
	playedAt: string,
};

/**
 *  再生の操作の要求（メニューバーの「再生」メニューと、OSのメディアキー・コントロールセンターなどから）
 * 
 *  再生キューと再生の制御はフロントエンドが持つため、操作はフロントエンド（`Player.svelte`）が
 *  行う。ウィンドウの中のキー操作と同じ動きになる。
 */
export type PlaybackControl = 
/**  再生と一時停止を切り替える */
{ type: "toggle" } | 
/**  再生する（再生中なら何もしない） */
{ type: "play" } | 
/**  一時停止する（一時停止中なら何もしない） */
{ type: "pause" } | 
/**  次の曲へ進む */
{ type: "next" } | 
/**  前の曲へ戻る（3秒以上再生していれば、再生中の曲の頭へ） */
{ type: "previous" } | 
/**  再生中の曲の、指定した位置へ移動する */
{ type: "seek"; 
/**  曲の頭からの秒数 */
position: number | null } | 
/**  音量を1段階上げる・下げる */
{ type: "volumeUp" } | { type: "volumeDown" } | 
/**  ミュートを切り替える */
{ type: "toggleMute" } | 
/**  シャッフルを切り替える */
{ type: "toggleShuffle" } | 
/**  リピートを切り替える（オフ → 全曲 → 1曲） */
{ type: "toggleRepeat" };

/**  保存する再生状態のうち、キュー以外の値 */
export type PlaybackCursor = {
	/**  音量（0.0〜1.0） */
	volume: number | null,
	/**  シャッフルが有効か */
	shuffle: boolean,
	repeat: RepeatMode,
	/**  キューの中の、再生していた曲の位置（何も再生していなければnull） */
	currentIndex: number | null,
};

/**
 *  再生エンジン（`playback`）からの通知
 * 
 *  `token`は、フロントエンドが再生する曲ごとに振った番号（`playback_play` / `playback_set_next`で
 *  渡したもの）。曲を切り替えた後に届いた、前の曲の通知を見分けるために使う。
 */
export type PlaybackEvent = 
/**  続けて再生する曲（`playback_set_next`で用意した曲）へ、切れ目なく切り替わった */
{ type: "advanced"; token: number; 
/**  曲の長さ（秒。ファイルから分からない場合はnull） */
duration: number | null } | 
/**  再生位置（再生中に一定の間隔で届く。シークの直後にも届く） */
{ type: "position"; token: number; 
/**  曲の頭からの秒数 */
position: number | null } | 
/**  曲が最後まで鳴り終わり、続けて再生する曲がなかった */
{ type: "ended"; token: number } | 
/**  再生を続けられなくなった（ファイルを読めない・出力デバイスを使えないなど）。再生は止まっている */
{ type: "failed"; token: number; error: AppError };

/**  保存する再生キュー（トラックIDの並び） */
export type PlaybackQueue = {
	/**  再生する順のトラックID */
	trackIds: string[],
	/**  シャッフルする前の順のトラックID（シャッフルが有効な時だけ。解除した時に、この順へ戻す） */
	originalTrackIds: string[] | null,
};

/**  再生を始めた曲の情報 */
export type PlaybackTrackInfo = {
	/**  曲の長さ（秒。ファイルから分からない場合はnull） */
	duration: number | null,
};

/**  プレイリストのデータモデル */
export type Playlist = {
	id: string,
	name: string,
	description: string | null,
	tracks: PlaylistTrack[],
	createdAt: string,
	updatedAt: string,
};

/**  プレイリスト内のトラック情報 */
export type PlaylistTrack = {
	trackId: string,
	position: number,
	addedAt: string,
};

/**  メタデータ更新の結果 */
export type RefreshMetadataResult = {
	updatedCount: number,
	skippedCount: number,
	errorCount: number,
	errors: string[],
};

/**  リピートの設定 */
export type RepeatMode = 
/**  リピートしない */
"off" | 
/**  キューの最後まで再生したら、先頭へ戻る */
"all" | 
/**  同じ曲を繰り返す */
"one";

/**
 *  音量の正規化に使うゲインとピーク（ReplayGainのタグ、またはEBU R128のタグから読み取る）
 * 
 *  ゲインはReplayGainの基準（-18 LUFS）に合わせたdB。ピークは最大振幅（1.0がフルスケール）。
 */
export type ReplayGain = {
	trackGain: number | null,
	trackPeak: number | null,
	albumGain: number | null,
	albumPeak: number | null,
};

/**  再スキャンの結果 */
export type RescanResult = {
	/**  新しく追加したトラック数 */
	addedCount: number,
	/**  変更を読み直したトラック数 */
	updatedCount: number,
	/**  移動・改名されたファイルに結び付けたトラック数（見つからない曲を、同じ曲として引き継いだ） */
	relinkedCount: number,
	/**  ファイルが見つからなくなり、見つからない曲にしたトラック数（ライブラリからは外さない） */
	missingCount: number,
	/**  ファイルが同じ場所に戻り、見つかる曲に戻したトラック数 */
	restoredCount: number,
	errorCount: number,
	errors: string[],
	/**  音楽ファイルが1件も見つからなかったため、見つからない曲にしなかった */
	missingSkipped: boolean,
};

/**  復元する再生状態 */
export type RestoredPlaybackState = {
	volume: number | null,
	shuffle: boolean,
	repeat: RepeatMode,
	/**  再生キュー（再生する順。ライブラリからなくなった曲・ファイルが見つからない曲は除く） */
	queue: Track[],
	/**  シャッフルする前の順のトラックID（`queue`にある曲だけ。シャッフルが無効ならnull） */
	originalTrackIds: string[] | null,
	/**  `queue`の中の、再生していた曲の位置（その曲がなくなっていれば、次の曲の位置。なければnull） */
	currentIndex: number | null,
};

/**  アプリケーション設定 */
export type Settings = {
	/**  表示の言語 */
	language: Language,
	/**  起動時に開く画面 */
	startupPage: StartupPage,
	/**  画面の配色 */
	theme: Theme,
	/**  アクセントカラー（`#rrggbb`） */
	accentColor: string,
	/**  音量の正規化 */
	volumeNormalization: VolumeNormalization,
	/**  ギャップレス再生（次の曲を先読みし、曲間に無音を入れずに続ける） */
	gaplessPlayback: boolean,
	/**  クロスフェードの秒数（0でクロスフェードしない） */
	crossfadeSeconds: number,
	/**  出力デバイスのID（nullはOSの既定のデバイス） */
	outputDeviceId: string | null,
	/**  ライブラリフォルダを監視し、ファイルの変更を自動で反映する */
	watchLibraryFolders: boolean,
	/**  ライブラリフォルダを定期的に再スキャンする間隔（分。0で再スキャンしない） */
	libraryScanIntervalMinutes: number,
};

/**  設定が保存された（設定ウィンドウでの変更をメインウィンドウに反映する） */
export type SettingsChanged = Settings;

/**  メニュー「Muspice について」: Aboutダイアログを表示する */
export type ShowAboutDialog = null;

/**  起動時に開く画面 */
export type StartupPage = 
/**  前回開いていた画面 */
"lastOpened" | 
/**  曲一覧 */
"songs";

/**  転送先デバイス（一覧表示用） */
export type SyncDevice = {
	id: string,
	name: string,
	/**  転送先のフォルダ */
	path: string,
	/**  ライブラリの全曲を同期するか */
	syncAll: boolean,
	/**  同期するプレイリスト（`.m3u8`も書き出す。全曲を同期しない場合は、曲もここから決まる） */
	playlistIds: string[],
	/**  同期の対象から外れた曲を、デバイスから削除するか */
	removeUnselected: boolean,
	/**  接続されているか（転送先のフォルダに、このデバイスの管理ファイルがあるか） */
	connected: boolean,
	/**  空き容量・全体の容量（バイト）。接続されていない場合は値なし */
	freeBytes: number | null,
	totalBytes: number | null,
	createdAt: string,
	lastSyncedAt: string | null,
};

/**  デバイスの設定（名前と同期する対象） */
export type SyncDeviceConfig = {
	name: string,
	syncAll: boolean,
	playlistIds: string[],
	removeUnselected: boolean,
};

/**  画面の配色 */
export type Theme = 
/**  ダーク */
"dark" | 
/**  ライト */
"light" | 
/**  OSの設定に従う */
"system";

/**  メニュー「サイドバーを表示/隠す」: サイドバーの表示を切り替える */
export type ToggleSidebar = null;

/**  音楽トラックのデータモデル */
export type Track = {
	id: string,
	filePath: string,
	fileName: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	/**  アルバムアーティスト（タグにない曲は値なし。一覧では、ない場合に`artist`でまとめる） */
	albumArtist: string | null,
	genre: string | null,
	year: number | null,
	trackNumber: number | null,
	discNumber: number | null,
	duration: number | null,
	fileSize: number,
	format: string,
	bitrate: number | null,
	sampleRate: number | null,
	isFavorite: boolean,
	rating: number,
	/**  再生回数（曲の半分か4分を聴いた回数） */
	playCount: number,
	/**  スキップ回数（再生回数に数える前に、別の曲へ移った回数） */
	skipCount: number,
	/**  最後に再生回数に数えた日時 */
	lastPlayedAt: string | null,
	createdAt: string,
	updatedAt: string,
	/**  音量の正規化に使うゲイン（タグにない項目は値なし） */
	replayGain: ReplayGain,
	/**  ファイルが見つからない（再スキャンで見つからなくなった曲。利用者が外すまで残す） */
	isMissing: boolean,
};

/**  音量の正規化（ReplayGain） */
export type VolumeNormalization = 
/**  補正しない */
"off" | 
/**  トラック単位のゲインで補正する（ない場合はアルバム単位） */
"track" | 
/**  アルバム単位のゲインで補正する（ない場合はトラック単位） */
"album";

/**  アプリ内の値をファイルへ書き出した結果 */
export type WriteMetadataResult = {
	/**  ファイルへ書き込んだトラック数 */
	writtenCount: number,
	/**  ファイルと同じ内容で、書き込まなかったトラック数 */
	unchangedCount: number,
	/**  ファイルが見つからず、飛ばしたトラック数 */
	skippedCount: number,
	/**  書き込めなかったトラック数 */
	errorCount: number,
	/**  書き込めなかったトラックの理由（ファイルごと） */
	errors: string[],
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

