// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  フォルダから音楽ファイルをインポート（バッチ処理最適化版） */
	importFolder: (folderPath: string, duplicateAction: DuplicateAction) => __TAURI_INVOKE<ImportResult>("import_folder", { folderPath, duplicateAction }),
	/**  すべてのトラックを取得 */
	getAllTracks: () => __TAURI_INVOKE<Track[]>("get_all_tracks"),
	/**  トラックを検索（FTS5 + LIKEフォールバック） */
	searchTracks: (query: string) => __TAURI_INVOKE<Track[]>("search_tracks", { query }),
	/**  トラックをフィルタリング */
	filterTracks: (filters: FilterOptions) => __TAURI_INVOKE<Track[]>("filter_tracks", { filters }),
	/**  ユニークなアーティスト一覧を取得 */
	getUniqueArtists: () => __TAURI_INVOKE<string[]>("get_unique_artists"),
	/**  ユニークなアルバム一覧を取得 */
	getUniqueAlbums: () => __TAURI_INVOKE<string[]>("get_unique_albums"),
	/**  ユニークなジャンル一覧を取得 */
	getUniqueGenres: () => __TAURI_INVOKE<string[]>("get_unique_genres"),
	/**  アルバム一覧（グループ化）を取得 */
	getAlbumsGrouped: () => __TAURI_INVOKE<AlbumGroup[]>("get_albums_grouped"),
	/**  アーティスト一覧（グループ化）を取得 */
	getArtistsGrouped: () => __TAURI_INVOKE<ArtistGroup[]>("get_artists_grouped"),
	/**  ジャンル一覧（グループ化）を取得 */
	getGenresGrouped: () => __TAURI_INVOKE<GenreGroup[]>("get_genres_grouped"),
	/**  トラックのメタデータを更新（データベースのみ） */
	updateTrackMetadata: (trackId: string, metadata: Metadata) => __TAURI_INVOKE<null>("update_track_metadata", { trackId, metadata }),
	/**  トラックのメタデータを更新（ファイルとデータベース両方） */
	updateTrackMetadataWithFile: (trackId: string, metadata: Metadata) => __TAURI_INVOKE<null>("update_track_metadata_with_file", { trackId, metadata }),
	/**  複数トラックのメタデータを一括更新（データベースのみ） */
	updateMultipleTracksMetadata: (trackIds: string[], metadata: Metadata) => __TAURI_INVOKE<null>("update_multiple_tracks_metadata", { trackIds, metadata }),
	/**  メタデータをバリデーション（フロントエンド用） */
	validateMetadataCommand: (metadata: Metadata) => __TAURI_INVOKE<null>("validate_metadata_command", { metadata }),
	/**  プレイリストを作成 */
	createPlaylist: (name: string) => __TAURI_INVOKE<Playlist>("create_playlist", { name }),
	/**  すべてのプレイリストを取得 */
	getPlaylists: () => __TAURI_INVOKE<Playlist[]>("get_playlists"),
	/**  プレイリストを削除 */
	deletePlaylist: (playlistId: string) => __TAURI_INVOKE<null>("delete_playlist", { playlistId }),
	/**  プレイリストの名前を変更 */
	renamePlaylist: (playlistId: string, name: string) => __TAURI_INVOKE<null>("rename_playlist", { playlistId, name }),
	/**  プレイリストにトラックを追加 */
	addTrackToPlaylist: (playlistId: string, trackId: string) => __TAURI_INVOKE<null>("add_track_to_playlist", { playlistId, trackId }),
	/**  プレイリストからトラックを削除 */
	removeTrackFromPlaylist: (playlistId: string, trackId: string) => __TAURI_INVOKE<null>("remove_track_from_playlist", { playlistId, trackId }),
	/**  プレイリスト内のトラックを並び替え */
	reorderPlaylistTracks: (playlistId: string, trackIds: string[]) => __TAURI_INVOKE<null>("reorder_playlist_tracks", { playlistId, trackIds }),
	/**  トラックのアルバムアートを取得 */
	getAlbumArt: (trackId: string) => __TAURI_INVOKE<{
	/**  Base64エンコードされた画像データ */
	data: string,
	/**  MIMEタイプ (image/jpeg, image/png など) */
	mimeType: string,
} | null>("get_album_art", { trackId }),
	/**  トラックのファイルパスを取得 */
	getTrackFilePath: (trackId: string) => __TAURI_INVOKE<string>("get_track_file_path", { trackId }),
	/**  現在再生中のトラックIDを設定 */
	setCurrentTrack: (trackId: string | null) => __TAURI_INVOKE<null>("set_current_track", { trackId }),
	/**  現在再生中のトラック情報を取得 */
	getCurrentTrack: () => __TAURI_INVOKE<{
	id: string,
	filePath: string,
	fileName: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	genre: string | null,
	year: number | null,
	trackNumber: number | null,
	discNumber: number | null,
	duration: number | null,
	fileSize: number,
	format: string,
	bitrate: number | null,
	sampleRate: number | null,
	isFavorite: boolean,
	rating: number,
	playCount: number,
	lastPlayedAt: string | null,
	createdAt: string,
	updatedAt: string,
} | null>("get_current_track"),
	/**  ファイルの場所をシステムのファイルマネージャーで開く */
	showInFolder: (path: string) => __TAURI_INVOKE<null>("show_in_folder", { path }),
	/**  お気に入りを切り替え */
	toggleFavorite: (trackId: string) => __TAURI_INVOKE<boolean>("toggle_favorite", { trackId }),
	/**  レーティングを設定 */
	setRating: (trackId: string, rating: number) => __TAURI_INVOKE<null>("set_rating", { trackId, rating }),
	/**  再生回数をインクリメント */
	incrementPlayCount: (trackId: string) => __TAURI_INVOKE<number>("increment_play_count", { trackId }),
	/**  お気に入りトラック一覧を取得 */
	getFavoriteTracks: () => __TAURI_INVOKE<Track[]>("get_favorite_tracks"),
	/**  最も再生されたトラック一覧を取得 */
	getMostPlayedTracks: (limit: number | null) => __TAURI_INVOKE<Track[]>("get_most_played_tracks", { limit }),
	/**  最近再生されたトラック一覧を取得 */
	getRecentlyPlayedTracks: (limit: number | null) => __TAURI_INVOKE<Track[]>("get_recently_played_tracks", { limit }),
	/**
	 *  トラックをライブラリから削除（データベースのみ）
	 *  ファイルは削除せず、データベースからのみ削除
	 */
	deleteTracksCommand: (trackIds: string[]) => __TAURI_INVOKE<number>("delete_tracks_command", { trackIds }),
	/**
	 *  トラックをライブラリとファイルシステムから削除
	 *  データベースとファイル両方を削除
	 */
	deleteTracksWithFilesCommand: (trackIds: string[]) => __TAURI_INVOKE<DeleteResult>("delete_tracks_with_files_command", { trackIds }),
	/**
	 *  ライブラリ全体のメタデータを更新
	 *  ファイルからtrack_numberとdisc_numberを再読み込み
	 */
	refreshLibraryMetadata: () => __TAURI_INVOKE<RefreshMetadataResult>("refresh_library_metadata"),
};

/* Types */
/**  アルバムアート情報 */
export type AlbumArt = {
	/**  Base64エンコードされた画像データ */
	data: string,
	/**  MIMEタイプ (image/jpeg, image/png など) */
	mimeType: string,
};

/**  アルバムグループ（アルバム表示用） */
export type AlbumGroup = {
	name: string,
	artist: string | null,
	trackCount: number,
	totalDuration: number,
	representativeTrackId: string,
	tracks: Track[],
};

/**
 *  アプリケーション全体で使用するエラー型
 * 
 *  serdeのadjacently tagged表現により `{ "code": "LOCK", "message": "..." }`
 *  形式でシリアライズされる。specta::Typeによりコードのリテラル型union
 *  としてTypeScriptへエクスポートされる。
 */
export type AppError = 
/**  ロック取得の失敗（DBロック・ステートロック） */
{ code: "LOCK"; message: string } | 
/**  データベース操作の失敗 */
{ code: "DATABASE"; message: string } | 
/**  対象（トラック・プレイリスト・ファイル等）が見つからない */
{ code: "NOT_FOUND"; message: string } | 
/**  入力バリデーションエラー */
{ code: "VALIDATION"; message: string } | 
/**  ファイルI/Oエラー */
{ code: "IO"; message: string } | 
/**  メタデータの抽出・書き込みエラー */
{ code: "METADATA"; message: string };

/**  アーティストグループ（アーティスト表示用） */
export type ArtistGroup = {
	name: string,
	albumCount: number,
	trackCount: number,
	totalDuration: number,
	representativeTrackId: string,
	albums: AlbumGroup[],
};

/**  削除失敗の詳細 */
export type DeleteFailure = {
	/**  トラックID */
	trackId: string,
	/**  ファイルパス */
	filePath: string,
	/**  失敗の理由 */
	reason: string,
};

/**  トラック削除の結果 */
export type DeleteResult = {
	/**  削除に成功したトラック数 */
	successCount: number,
	/**  削除に失敗したトラック数 */
	failedCount: number,
	/**  削除に失敗したトラックの詳細 */
	failedTracks: DeleteFailure[],
};

/**  重複ファイルの処理方法 */
export type DuplicateAction = "Skip" | "Replace";

/**  フィルタオプション */
export type FilterOptions = {
	artist?: string | null,
	album?: string | null,
	genre?: string | null,
};

/**  ジャンルグループ（ジャンル表示用） */
export type GenreGroup = {
	name: string,
	trackCount: number,
	totalDuration: number,
	representativeTrackId: string,
	tracks: Track[],
};

/**  フォルダから音楽ファイルをインポートする結果 */
export type ImportResult = {
	importedCount: number,
	skippedCount: number,
	errorCount: number,
	errors: string[],
};

/**  メタデータのデータモデル */
export type Metadata = {
	title?: string | null,
	artist?: string | null,
	album?: string | null,
	genre?: string | null,
	year?: number | null,
	trackNumber?: number | null,
	discNumber?: number | null,
	albumArtist?: string | null,
	composer?: string | null,
};

/**  プレイリストのデータモデル */
export type Playlist = {
	id: string,
	name: string,
	description: string | null,
	tracks: PlaylistTrack[],
	createdAt: string,
	updatedAt: string,
};

/**  プレイリスト内のトラック情報 */
export type PlaylistTrack = {
	trackId: string,
	position: number,
	addedAt: string,
};

/**  メタデータ更新の結果 */
export type RefreshMetadataResult = {
	updatedCount: number,
	skippedCount: number,
	errorCount: number,
	errors: string[],
};

/**  音楽トラックのデータモデル */
export type Track = {
	id: string,
	filePath: string,
	fileName: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	genre: string | null,
	year: number | null,
	trackNumber: number | null,
	discNumber: number | null,
	duration: number | null,
	fileSize: number,
	format: string,
	bitrate: number | null,
	sampleRate: number | null,
	isFavorite: boolean,
	rating: number,
	playCount: number,
	lastPlayedAt: string | null,
	createdAt: string,
	updatedAt: string,
};

